/*!
 * \file ds3231.c
 * \brief Clocks
 *
 * Software License Agreement:
 * 
 * This code is generated by the Embedd platform and is free to use, distribute, 
 * and modify by anyone, provided that a reference to the Embedd platform is 
 * included in any distributed or derivative works.
 * 
 * The code is provided "as is" without warranty of any kind, either expressed or 
 * implied, including but not limited to the implied warranties of merchantability 
 * and fitness for a particular purpose.
 * 
 * By using this code, you agree to acknowledge the Embedd platform in your 
 * projects or documentation where this code is utilized.
 * 
 * © 2024 Embedd Limited. All Rights Reserved.
 */

#include "ds3231.h"





const ds3231_api_t ds3231_api = {
    .ds3231_write_reg = &ds3231_write_reg,
    .ds3231_read_reg = &ds3231_read_reg,
};
