/*
 * \file ds3231_events.h
 * \brief Clocks Events.
 *
 * This file defines event IDs for Clocks,
 * specifically the Clocks. These ID represent various status changes
 * or general events from the device.
 *
 * Software License Agreement:
 * 
 * This code is generated by the Embedd platform and is free to use, distribute, 
 * and modify by anyone, provided that a reference to the Embedd platform is 
 * included in any distributed or derivative works.
 * 
 * The code is provided "as is" without warranty of any kind, either expressed or 
 * implied, including but not limited to the implied warranties of merchantability 
 * and fitness for a particular purpose.
 * 
 * By using this code, you agree to acknowledge the Embedd platform in your 
 * projects or documentation where this code is utilized.
 * 
 * © 2024 Embedd Limited. All Rights Reserved.
 */
#ifndef _SRC_DS3231_EVENTS_H
#define _SRC_DS3231_EVENTS_H

#include <stdint.h>
#include "embedd_device.h"

enum {
/* --------------------------------------------------------------------------
 * Event name: Alarm 1 Event
 * Event description: Triggered when the time and date match the values stored in the Alarm 1 registers.
 * -------------------------------------------------------------------------- */
  DS3231_ALARM_1_EVENT_EVENT_ID = 0x34e0f28,
/* --------------------------------------------------------------------------
 * Event name: Alarm 2 Event
 * Event description: Triggered when the time and date match the values stored in the Alarm 2 registers.
 * -------------------------------------------------------------------------- */
  DS3231_ALARM_2_EVENT_EVENT_ID = 0x2a86bbda,
};

#endif//_SRC_DS3231_EVENTS_H
