/*!
 * \file ds3231_registers.c
 * \brief Clocks
 *
 * Software License Agreement:
 * 
 * This code is generated by the Embedd platform and is free to use, distribute, 
 * and modify by anyone, provided that a reference to the Embedd platform is 
 * included in any distributed or derivative works.
 * 
 * The code is provided "as is" without warranty of any kind, either expressed or 
 * implied, including but not limited to the implied warranties of merchantability 
 * and fitness for a particular purpose.
 * 
 * By using this code, you agree to acknowledge the Embedd platform in your 
 * projects or documentation where this code is utilized.
 * 
 * © 2024 Embedd Limited. All Rights Reserved.
 */

#include "embedd_device.h"
#include "embedd_utils.h"
#include "embedd_hal.h"

#include "ds3231_registers.h"
#include "ds3231_data_types.h"

/* --------------------------------------------------------------------------
 * Clocks register access methods
 * -------------------------------------------------------------------------- */

EMBEDD_RESULT ds3231_write_reg(embedd_device_t* dev, uint32_t reg_addr, void* data, uint32_t data_size, uint32_t delay) {
    EMBEDD_RESULT result = EMBEDD_RESULT_ERR;
    if (dev == NULL ||
        dev->bus == NULL ||
        dev->bus->write == NULL ||
        dev->data == NULL ||
        data == NULL) {
        return result;
    }
    ds3231_data_t* _data = (ds3231_data_t*)dev->data;
    uint32_t msg_size = DS3231_REGISTER_ADDR_SIZE + data_size ;
    uint8_t* _out_ptr = _data->out_buf;
    embedd_pack( _out_ptr, &reg_addr, DS3231_REGISTER_ADDR_SIZE );
    embedd_pack( _out_ptr + DS3231_REGISTER_ADDR_SIZE, data, data_size );
    result = dev->bus->write( dev, _out_ptr, msg_size );
    if(result != EMBEDD_RESULT_OK) {
      return result;
    }
    embedd_hal_sleep( delay );
    return result;
}

EMBEDD_RESULT ds3231_read_reg(embedd_device_t* dev, uint32_t reg_addr, void* data, uint32_t data_size, uint32_t delay) {
    EMBEDD_RESULT result = EMBEDD_RESULT_ERR;
    if (dev == NULL ||  
        dev->bus == NULL ||
        dev->bus->write == NULL || 
        dev->bus->read == NULL ||
        dev->data == NULL ||
        data == NULL) {
        return result;
    }
    ds3231_data_t* _data = (ds3231_data_t*)dev->data;
    uint32_t msg_size = DS3231_REGISTER_ADDR_SIZE;
    uint8_t* _out_ptr = _data->out_buf;
    uint8_t* _in_ptr  = _data->in_buf;
    embedd_pack( _out_ptr, &reg_addr, DS3231_REGISTER_ADDR_SIZE );
    result = dev->bus->write( dev, _out_ptr, msg_size );
    if( result != EMBEDD_RESULT_OK ) {
      return result;
    }
    embedd_hal_sleep(delay);
    result = dev->bus->read( dev, _in_ptr, data_size );
    if( result != EMBEDD_RESULT_OK ) {
      return result;
    }
    embedd_pack( data, _in_ptr, data_size );
    return result;
}

