/*!
 * \file embedd_utils.c
 * \brief Implementaton of miscellaneous functions
 *
 * Software License Agreement:
 * 
 * This code is generated by the Embedd platform and is free to use, distribute, 
 * and modify by anyone, provided that a reference to the Embedd platform is 
 * included in any distributed or derivative works.
 * 
 * The code is provided "as is" without warranty of any kind, either expressed or 
 * implied, including but not limited to the implied warranties of merchantability 
 * and fitness for a particular purpose.
 * 
 * By using this code, you agree to acknowledge the Embedd platform in your 
 * projects or documentation where this code is utilized.
 * 
 * © 2024 Embedd Limited. All Rights Reserved.
 */

#include  "embedd_utils.h"


size_t  embedd_copy(void* dst, void* src, size_t Size) {
    memcpy( dst, src, Size );
    return Size;
}

size_t embedd_pack(void* dst, void* src, size_t Size) {
    if (dst == NULL || src == NULL) {
        return 0;
    }
    if (Size == 0) {
        return 0;
    }

    const uint8_t *srcPtr = (const uint8_t *)src + Size - 1;
    uint8_t *dstPtr = (uint8_t *)dst;

    for (size_t i = 0; i < Size; ++i) {
        *dstPtr++ = *srcPtr--;
    }

    return Size;
}
