/*!
 * \file embedd_i2c.c
 * \brief Provides implementations of functions related to I2C bus
 *
 * Software License Agreement:
 * 
 * This code is generated by the Embedd platform and is free to use, distribute, 
 * and modify by anyone, provided that a reference to the Embedd platform is 
 * included in any distributed or derivative works.
 * 
 * The code is provided "as is" without warranty of any kind, either expressed or 
 * implied, including but not limited to the implied warranties of merchantability 
 * and fitness for a particular purpose.
 * 
 * By using this code, you agree to acknowledge the Embedd platform in your 
 * projects or documentation where this code is utilized.
 * 
 * © 2024 Embedd Limited. All Rights Reserved.
 */

#include "embedd_i2c.h"

#include "embedd_device.h"

EMBEDD_RESULT embedd_i2c_set_dev_config(const struct embedd_device_t *dev, embedd_i2c_dev_cfg_t *config) {
    if (config != NULL) {
        embedd_i2c_dev_cfg_t *current_cfg = embedd_i2c_get_dev_config(dev);
        if ((current_cfg != NULL) && embedd_i2c_is_sub_addr_valid(config->addr)) {
            current_cfg->addr = config->addr;
            return EMBEDD_RESULT_OK;
        }
    }
    return EMBEDD_RESULT_ERR;
}

embedd_i2c_dev_cfg_t *embedd_i2c_get_dev_config(const struct embedd_device_t *dev) {
    if ((dev != NULL) && (dev->config != NULL) && (dev->config->bus_cfg.bus_type == EMBEDD_BUS_TYPE_I2C)) {
        return (embedd_i2c_dev_cfg_t *)dev->config->bus_cfg.configs;
    }

    return NULL;
}
