/*!
 * \file embedd_event_types.h
 * \brief Provides data types related to events
 *
 * Software License Agreement:
 * 
 * This code is generated by the Embedd platform and is free to use, distribute, 
 * and modify by anyone, provided that a reference to the Embedd platform is 
 * included in any distributed or derivative works.
 * 
 * The code is provided "as is" without warranty of any kind, either expressed or 
 * implied, including but not limited to the implied warranties of merchantability 
 * and fitness for a particular purpose.
 * 
 * By using this code, you agree to acknowledge the Embedd platform in your 
 * projects or documentation where this code is utilized.
 * 
 * © 2024 Embedd Limited. All Rights Reserved.
 */

#ifndef _SRC_EMBEDD_EVENT_TYPES_H
#define _SRC_EMBEDD_EVENT_TYPES_H

#include "embedd_device.h"

/*!
 *  \struct EventSource
 *  \brief  event source data type
 *
 *  \param  device  pointer to device object
 *  \param  id      event id
 */
struct EventSource {
    embedd_device_t *device;
    uint32_t event_id;
};

/*!
 *  \typedef  embedd_callback_t
 *  \brief    event callback data type
 */
typedef void (*embedd_callback_t)(struct EventSource*);

#define     VOID_EVENT_ID   (0)

#endif //_SRC_EMBEDD_EVENT_TYPES_H
