/*!
 * \file embedd_i2c.h
 * \brief Provides data types and functions related to I2C bus
 *
 * Software License Agreement:
 * 
 * This code is generated by the Embedd platform and is free to use, distribute, 
 * and modify by anyone, provided that a reference to the Embedd platform is 
 * included in any distributed or derivative works.
 * 
 * The code is provided "as is" without warranty of any kind, either expressed or 
 * implied, including but not limited to the implied warranties of merchantability 
 * and fitness for a particular purpose.
 * 
 * By using this code, you agree to acknowledge the Embedd platform in your 
 * projects or documentation where this code is utilized.
 * 
 * © 2024 Embedd Limited. All Rights Reserved.
 */

#ifndef _SRC_EMBEDD_I2C_H
#define _SRC_EMBEDD_I2C_H

#include <stdbool.h>

#include "embedd_hal.h"

/*!
 *  \def   EMBEDD_I2C_ADDR_FIRST_7BIT
 *  \brief The first available 7-bit I2C address
 */
#define EMBEDD_I2C_ADDR_FIRST_7BIT 0x08

/*!
 *  \def   EMBEDD_I2C_ADDR_LAST_7BIT
 *  \brief The last available 7-bit I2C address
 */
#define EMBEDD_I2C_ADDR_LAST_7BIT 0x77

/*!
 *  \def   EMBEDD_I2C_ADDR_FIRST_10BIT
 *  \brief The first I2C address which is only available for 10-bit address range
 */
#define EMBEDD_I2C_ADDR_FIRST_10BIT 0x80

/*!
 *  \def   EMBEDD_I2C_ADDR_LAST_10BIT
 *  \brief The last I2C address which is only available for 10-bit address range
 */
#define EMBEDD_I2C_ADDR_LAST_10BIT 0x3FF

/*!
 *  \struct   embedd_i2c_dev_cfg_t
 *  \brief    conficurations related to I2C device
 *
 *  \param    addr device's address on I2C bus
 */
typedef struct embedd_i2c_dev_cfg_t {
    uint16_t addr;
} embedd_i2c_dev_cfg_t;

/*!
 *  \typedef  embedd_bus_i2c_t
 *  \brief    definition of I2C bus object type
 */
typedef embedd_bus_t embedd_bus_i2c_t;

/*!
 *  \fn       embedd_i2c_set_dev_config
 *  \brief    writes I2C configuration into a device object
 *
 *  \param    dev    pointer to a device object which the configuration should be written to
 *  \param    config a desired I2C configuration
 *
 *  \result   EMBEDD_RESULT_OK or EMBEDD_RESULT_ERR
 */
EMBEDD_RESULT embedd_i2c_set_dev_config(const struct embedd_device_t *dev, embedd_i2c_dev_cfg_t *config);

/*!
 *  \fn       embedd_i2c_get_dev_config
 *  \brief    reads I2C configuration from the device object
 *
 *  \param    dev  pointer to a device object which the configuration should be read from
 *
 *  \result   pointer to the I2C device's configuration or NULL
 */
embedd_i2c_dev_cfg_t *embedd_i2c_get_dev_config(const struct embedd_device_t *dev);

/*!
 *  \fn       embedd_i2c_is_sub_addr_valid
 *  \brief    Verify whether the provided I2C sub address is in available for general use
 *
 *  \param    addr  I2C address which should be verified
 *
 *  \result   true - if the addess is in the available range. Otherwise false.
 */
static inline bool embedd_i2c_is_sub_addr_valid(uint16_t addr) {
    if (((addr >= EMBEDD_I2C_ADDR_FIRST_7BIT) && (addr <= EMBEDD_I2C_ADDR_LAST_7BIT)) ||
        ((addr >= EMBEDD_I2C_ADDR_FIRST_10BIT) && (addr <= EMBEDD_I2C_ADDR_LAST_10BIT))) {
        return true;
    }

    return false;
}

#endif  //_SRC_EMBEDD_I2C_H
