/*!
 * \file embedd_event_manager_cfg.h
 * \brief Contains event manager configuration
 *
 * Software License Agreement:
 * 
 * This code is generated by the Embedd platform and is free to use, distribute, 
 * and modify by anyone, provided that a reference to the Embedd platform is 
 * included in any distributed or derivative works.
 * 
 * The code is provided "as is" without warranty of any kind, either expressed or 
 * implied, including but not limited to the implied warranties of merchantability 
 * and fitness for a particular purpose.
 * 
 * By using this code, you agree to acknowledge the Embedd platform in your 
 * projects or documentation where this code is utilized.
 * 
 * © 2024 Embedd Limited. All Rights Reserved.
 */

#ifndef _SRC_EMBEDD_EVENT_MGR_CFG_H
#define _SRC_EMBEDD_EVENT_MGR_CFG_H
  
/*!
 *          Maximum count of events id processed by event manager
 */
#define     EMBEDD_EVENT_MGR_MAX_ACTIVE_ID_COUNT    (2U)

/*!
 *          Maximum count of items in callback table for each event id
 */
#define     EMBEDD_EVENT_MGR_MAX_CB_FOR_ID_COUNT    (2U)

/*!
 *          Maximum count of items in queue
 */
#define     EMBEDD_EVENT_MGR_MAX_QUEUE_ITEMS_COUNT  (4U)

/*!
 *          If this parameter is 1 events manager will process 
 *          queue by one item in queue
 *          If this parameter is 0 events manager will process
 *          all items in queue
 */
#define     EMBEDD_EVENT_MGR_PROCESS_ONE_ITEM       (1U)

 
#endif //_SRC_EMBEDD_EVENT_MGR_CFG_H
