/*!
 * \file embedd_event.c
 * \brief Provides 'weak' definitions of event interface
 *
 * Software License Agreement:
 * 
 * This code is generated by the Embedd platform and is free to use, distribute, 
 * and modify by anyone, provided that a reference to the Embedd platform is 
 * included in any distributed or derivative works.
 * 
 * The code is provided "as is" without warranty of any kind, either expressed or 
 * implied, including but not limited to the implied warranties of merchantability 
 * and fitness for a particular purpose.
 * 
 * By using this code, you agree to acknowledge the Embedd platform in your 
 * projects or documentation where this code is utilized.
 * 
 * © 2024 Embedd Limited. All Rights Reserved.
 */

#include  "embedd_event.h"

__attribute__((weak)) EMBEDD_RESULT embedd_event_manager_init() { return EMBEDD_RESULT_OK; }
__attribute__((weak)) EMBEDD_RESULT embedd_event_manager_deinit() { return EMBEDD_RESULT_OK; }
__attribute__((weak)) EMBEDD_RESULT embedd_event_manager_register_callback(  uint32_t id, embedd_callback_t cb ) { return EMBEDD_RESULT_OK; }
__attribute__((weak)) EMBEDD_RESULT embedd_event_manager_register_oneshot(   uint32_t id, embedd_callback_t cb ) { return EMBEDD_RESULT_OK; }
__attribute__((weak)) EMBEDD_RESULT embedd_event_manager_unregister_callback(uint32_t id, embedd_callback_t cb ) { return EMBEDD_RESULT_OK; }
__attribute__((weak)) EMBEDD_RESULT embedd_event_manager_process_events_enable() { return EMBEDD_RESULT_OK; }
__attribute__((weak)) EMBEDD_RESULT embedd_event_manager_process_events_disable() { return EMBEDD_RESULT_OK; }

__attribute__((weak)) EMBEDD_RESULT embedd_event_manager_process() { return EMBEDD_RESULT_OK; }
__attribute__((weak)) EMBEDD_RESULT embedd_event_manager_trigger(uint32_t event_id, void *device) { return EMBEDD_RESULT_OK; }
